esp-rs/esp-generate

Cargo.lock
Cargo.toml
src/main.rs
src/tui.rs
template/.cargo/config.toml
template/.github/workflows/rust_ci.yml
template/Cargo.toml
template/build.rs
template/src/bin/async_main.rs
template/src/bin/main.rs

- Use Rhai to check conditions
- Deduplicate if statements for `#` and `//`.
- Bump dependencies
I've generated a few projects and they seem sane.

Minor improvements

---

src/main.rs
template/.cargo/config.toml
template/.vscode/settings.json
template/Cargo.toml
template/rust-toolchain.toml
template/src/bin/async_main.rs
template/src/bin/main.rs

- use current HAL and other dependencies
- add a `.vscode/settings.json`
- some simplification of the template because we now support expressions as conditions

Use current dependencies

---

src/main.rs

- Add descriptions for command-line arguments
- Use `?` in favour of `unwrap`
- Small cleanup/refactoring

Miscellaneous cleanup/improvements

---

.github/workflows/ci.yml
CHANGELOG.md
src/tui.rs

- Escape now goes back if on a nested option and quits if on the main menu
- The user needs to confirm quitting the tui

Ask for confirmation when leaving

---

CHANGELOG.md
template/src/bin/async_main.rs
template/src/bin/main.rs

Examples hint

---

CHANGELOG.md
src/main.rs

If not, the generated code will not work
Fixes #64

Verify every dependency is required

---

template/build.rs

See https://github.com/esp-rs/esp-hal/issues/3048#issuecomment-2618577498

Prevent problems with flip-link

---

CHANGELOG.md
Cargo.toml
src/main.rs
src/tui.rs

This PR implements line counting/wrapping so we don't waste vertical space, as well as adds ability to display extra help lines. Currently used to display what's required, but we can do better with it.

Display help text

---

CHANGELOG.md
Cargo.lock
Cargo.toml
build.rs
src/main.rs
src/tui.rs
template/template.yaml

Use YAML template description, auto-generate help

---

CHANGELOG.md
template/.devcontainer/devcontainer.json
template/.vscode/extensions.json

See https://github.com/esp-rs/esp-generate/pull/109#pullrequestreview-2610890220

Update devcontainer extensions

---

build.rs
src/main.rs

store the template in the template files too

---

CHANGELOG.md
src/main.rs
template/template.yaml

Exclude template.yaml from the output

---

CHANGELOG.md
template/build.rs

Provide esp-wifi help

---

CHANGELOG.md
README.md
template/.cargo/config.toml
template/Cargo.toml
template/build.rs
template/template.yaml
template/tests/async_hello_test.rs
template/tests/hello_test.rs
xtask/src/main.rs

Generate embedded tests

---

CHANGELOG.md
src/main.rs
template/Cargo.toml

Noticed that esp-wifi/smoltcp is not enabled even if smoltcp is generated. Also, embassy-net is only added when embassy is present.

Enable the smoltcp feature

---

CHANGELOG.md
src/check.rs

Fix parsing espflash version

---

CHANGELOG.md
src/tui.rs

Fixes esp-generate in the vscode terminal. Applies a different color scheme for apple terminal
Closes #172

Apply fallback style for quirky terminals

---

CHANGELOG.md
template/Cargo.toml
template/src/bin/async_main.rs
template/template.yaml
xtask/src/main.rs

Test each option for each base template, fix build errors, pin esp-hal

---

.github/workflows/cd.yml

Take 2 due to manually replacing it in #190 instead of search and replace 😓

Update ubuntu runner

---

CHANGELOG.md
Cargo.toml
src/main.rs
src/tui.rs

closes https://github.com/esp-rs/esp-generate/issues/203

use `anyhow::bail` instead of log+exit
