esp-rs/esp-generate

.github/workflows/ci.yml, src/main.rs, template/rust-toolchain.toml
- Adds some basic CI
- We may need to come with a better strategy, but at least we are verifying some stuff already.
- Example run: https://github.com/SergioGasquez/esp-generate/actions/runs/11158725726
- Adds a `rust-toolchain.toml` file
- Validates, in a very simple way, the arguments
- Unify the `stack-protector` name
=> Minor improvements - Part 2

README.md
While trying to follow the steps in the `README.md` I found that the reference to this repo is outdated. Opened this PR to fix it.
=> Fix repository reference in `README.md`

src/main.rs
=> Make the 'ble' and 'wifi' options mutually exclusive

src/main.rs
Closes #15
Probably we should set up logging so we can print a warning, but I've opened #28 and we can do this in a separate PR.
=> Check if the current directory is in a git repo already, and only initialize if not

.github/workflows/ci.yml, xtask/src/main.rs
- Adds a `--all-combinations` flag to the `check` command
- Modified the workflow to use that flag when running scheduled, and when running it manually we should be able to select if we want the flag or not
- I couldnt test this, yet
CI test run: https://github.com/SergioGasquez/esp-generate/actions/runs/11570938398
=> Check all option combinations in CI

template/Cargo.toml
Fixes #17 
With this it's possible to just copy the code from `wifi_dhcp`, `wifi_ble`, `wifi_embassy_dhcp` and `wifi_embassy_ble` examples (using the correct generator options, minus chip specific `cfg-if`s in the example) and have them working
=> Include correct dependencies and features by options

src/main.rs
- list available options in `--help` (closes #32)
- use `target` from `esp-metadata`, avoid duplication
=> Minor improvements

CHANGELOG.md, README.md, src/main.rs, src/tui.rs, template/.helix/languages.toml, template/.vscode/settings.json
Mostly fixes #42
I will admit I don't know how to configure neovim, but I've added support for the editor I use anyway.
I could have added editors under the `optional` section but i felt as if having deeper nested selection was a worse experience. Can move it if you want me to
I snuck in space to select as well as that is quite a common key in these terminal interfaces.
=> Editor select

CHANGELOG.md, src/tui.rs
This is a very small change, but now that there are two sub-menus it could get annoying if you navigate back and forth if you're moved back to the top all the time.
=> remember position in previous menus

.github/workflows/cd.yml
Automates creating the binary artifacts and publishing the package to crates.io.  The release process is basically copied from `espup`.
We need to build the package before publishing as it needs to create the `template_files.rs`, and for this same reason, we need `--allow-dirty`
- [ ] We need to add the `${{ secrets.CARGO_API_KEY }}` secret
Test release in my fork https://github.com/SergioGasquez/esp-generate/actions/runs/11891708349
=> Add release process

.github/workflows/ci.yml, CHANGELOG.md, src/main.rs, template/Cargo.toml, template/build.rs, template/src/bin/async_main.rs, template/src/bin/main.rs, xtask/src/main.rs
This started as a PR to upgrade the deps to the latest dependencies but ended up being a bit more:
- Updates deps to latest esp-hal releases and adapt code
- CI was not failing when one option combination failed, now it bails
- Use systimer in embassy template for all targets but esp32
CI run checking all combinations: https://github.com/SergioGasquez/esp-generate/actions/runs/11950996040
=> Udpate to latest release and various fixes/improvements

CHANGELOG.md, src/main.rs, template/Cargo.toml
Closes #59 
In the very beginning it was easier to not support the coex - case (because IF conditions were very inflexible). Now it's easy to support it
=> Support COEX

CHANGELOG.md, src/main.rs, template/Cargo.toml, template/diagram.json, template/wokwi.toml, xtask/Cargo.lock
With this change the generated bin will have the project name instead of `main`, this helps with using esp-template in Wokwi
=> Add bin section

CHANGELOG.md, src/main.rs, template/build.rs, template/src/bin/async_main.rs, template/src/bin/main.rs
- include version of `esp-generate` in the generated code
- use `rustc-link-arg` instead of `rustc-link-arg-bin`
=> Generator version

CHANGELOG.md, template/.devcontainer/Dockerfile, template/.devcontainer/devcontainer.json
The `dev-container` option  (set using `esp-generate --chip esp32 -o dev-container your-project`) does not generate a valid dev-container configuration. The templated parameters are never substituted, which leads to syntax errors, when opening the container. 
This PR updates the dev-container.json file template to use the key/value based substitution found in other files.
=> Fix dev-container templating

CHANGELOG.md, template/.helix/languages.toml, template/.vscode/settings.json
It seems that rust-analyzer doesn't support custom toolchains, but the documentation suggests adding an override such that rust-analzer runs on the stable toolchain: https://rust-analyzer.github.io/manual.html#toolchain.
=> Use stable toolchain for rust-analyzer on xtensa targets

CHANGELOG.md, Cargo.lock, Cargo.toml, src/main.rs
Tested with `--chip=esp32s3  test-c6 -o alloc -o ble -o embassy --headless` and results in: 
```toml
[package]
edition = "2021"
name    = "test-c6"
version = "0.1.0"
[[bin]]
name = "test-c6"
path = "./src/bin/async_main.rs"
[dependencies]
bleps = { git = "https://github.com/bjoernQ/bleps", package = "bleps", rev = "a5148d8ae679e021b78f53fd33afb8bb35d0b62e", features = [
"async",
"macros",
] }
critical-section = "1.2.0"
embassy-executor = { version = "0.6.0", features = ["task-arena-size-12288"] }
embassy-time = { version = "0.3.1", features = ["generic-queue-8"] }
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"
esp-alloc = { version = "0.5.0" }
esp-backtrace = { version = "0.14.2", features = [
"esp32s3",
"exception-handler",
"panic-handler",
"println",
] }
esp-hal = { version = …
```
=> Use taplo to format the resulting Cargo.toml

template/Cargo.toml
The `edge-*` crates got new releases so we can use them instead of the git revs.
However, I wonder if we should include them at all by default?
e.g. `edge-dhcp` is only useful for AP but I assume that's not very common.
Maybe we should add a hint like `# for more networking protocol support visit https://crates.io/crates/edge-net` instead?
And it seems those crates are async only - so we shouldn't include them (or the hint) if we don't generate for async?
I'm open to suggestions and happy to change this PR accordingly
=> Use published `edge-*` crates

template/.github/workflows/rust_ci.yml
- `GITHUB_TOKEN` is only required when used `xtensa-toolchain` action
- `--color always` is redundant, we have `CARGO_TERM_COLOR: always`
=> Minor CI cleanups

CHANGELOG.md, src/check.rs, src/main.rs
After generation this will show s.th. like this
It's just to hint the user in case of any problems - they can still update / install tools after the project is generated.
Closes #63
=> Check rustc+cargo, espflash, probe-rs

CHANGELOG.md, template/build.rs
I stumbled upon this "by accident" but thought it might be a good idea - but maybe I'm just a little bit too excited about this so if we don't think it's useful it's fine.
It will look like this
While users can't run into it with a freshly generated project they might add and change things which might make them run into it
I guess there are more things that could be helpful - I just didn't want to waste too much time with something we don't think is useful
=> Make linker errors more helpful

CHANGELOG.md, src/main.rs, src/tui.rs, template/.cargo/config.toml, template/Cargo.toml, template/rust-toolchain.toml, template/src/bin/async_main.rs, template/src/bin/main.rs
This PR adds support for else-if in templates, which will be useful if we are going to have more options that are mutually exclusive.
The PR also reorders log setup to before HAL initialization, so that the HAL's init process may be able to print logs if such configured.
=> Support `ELIF` (else-if) in templates

CHANGELOG.md, src/main.rs, src/tui.rs
This may be somewhat of a UX regression, as we no longer enable/disable options automatically, but instead dynamically change whether an item is active or not. We could still reintroduce the automatic requirement selection (which I think may be slightly confusing), but that is a tricky problem to solve now, especially if options get into a requires-requires not cycle.
I'm slightly worried about the regression, because now if we have exclusive options, those don't deselect each other, but the user has to manually toggle them. This also means that the "neither one selected" must be a valid option, although even the previous method didn't handle "option A enables option B enables option C" recursive cases so maybe this is just trading limitations.
The goal of this PR is to enable "Allow …
=> Replace automatic option enable/disable with a list of requirements

.cargo/config.toml, .github/workflows/ci.yml, xtask/src/main.rs
Before this PR we were testing the same combination several times.
```
[2025-02-10T15:17:48Z INFO  xtask] ["alloc", "probe-rs"]
[2025-02-10T15:17:48Z INFO  xtask] ["alloc", "probe-rs"]
[2025-02-10T15:17:48Z INFO  xtask] ["alloc", "probe-rs", "wifi"]
[2025-02-10T15:17:48Z INFO  xtask] ["alloc", "probe-rs", "wifi"]
[2025-02-10T15:17:48Z INFO  xtask] ["alloc", "alloc", "probe-rs", "wifi"]
[2025-02-10T15:17:48Z INFO  xtask] ["alloc", "alloc", "probe-rs", "wifi"]
```
This PR hopefully cuts down the CI time a bit. We also seem to support `wifi && ble` at least in some places in the templates, so I've removed the filter for them.
The PR also removes the `push` trigger because for some reason, everything ran twice on each PR.
=> Deduplicate redundant "All options"

CHANGELOG.md, Cargo.toml, src/config.rs, src/lib.rs, src/main.rs, src/template.rs, src/tui.rs, xtask/Cargo.lock, xtask/Cargo.toml, xtask/src/main.rs
I meant to do this as part of #103 but that was merged before I started :) For current options, the PR returns the same lists for both `all_configurations` and `!all_configurations` as before, but we no longer have to maintain that list.
=> Test from yaml

.github/workflows/ci.yml, xtask/src/main.rs
`esp-generate` fails to compile for some reason on Windows, when ran by the xtask from another directory. I don't really know why, and why this happens with `--release`, but removing that seems to work just fine. `--no-default-features` disables the update checker, which is unnecessary for local/CI testing.
=> Run generate in debug mode

.github/workflows/ci.yml, xtask/src/main.rs
This might improve CI - we'll see
=> Maybe CI improvements

CHANGELOG.md, template/.devcontainer/devcontainer.json
Doing recommended migration of  `crates` to `dependi`  vscode extension.
=> Replace deprecated vscode extension in devcontainer config

CHANGELOG.md, README.md, template/Cargo.toml, template/src/bin/main.rs, template/template.yaml
=> Add a switch to enable unstable esp-hal features

CHANGELOG.md, src/tui.rs
Adds the ability to select separate colors for active/inactive items, and implements https://github.com/esp-rs/esp-generate/pull/113#issuecomment-2655993230
I did tweak the inactive colors a bit compared to #113 so that they are a bit more readable.
Active item:
Inactive item:
=> Use separate inactive highlight colors

CHANGELOG.md, src/main.rs, src/tui.rs, template/template.yaml
The result of this PR is this screenshot for the S2 (note the lack of BLE option):
Hopefully this isn't too visually busy. We refer to the option names in multiple places, so we might as well show their names.
=> Display names of options, completely remove chip-incompatible settings

CHANGELOG.md, src/config.rs, src/template.rs, src/tui.rs, xtask/src/main.rs
Selection groups behave similar to radio groups in the web: only one option in a group may be selected. They are meant to allow selecting exclusive features (such as log vs defmt), and also allow requiring "one-of-N" options (i.e. defmt requires esp-println, defmt-rtt or rtt-target).
This was pretty hard to get right, evaluating the requirements turned out a bit more complicated than I wanted.
=> Implement selection groups

.github/workflows/ci.yml, xtask/src/main.rs
I've messed up a few things that only fail during linking, so let's have the ability to build configs if we want to - and also during the night.
=> Allow building test projects, build during scheduled checks

src/config.rs, src/template.rs, xtask/src/main.rs
=> Check more

CHANGELOG.md, Cargo.lock, Cargo.toml, xtask/Cargo.lock, xtask/Cargo.toml
Safety check of CI running `all-combinations`: https://github.com/SergioGasquez/esp-generate/actions/runs/13627942602
=> Prepare 0.3.1 release

template/.github/workflows/rust_ci.yml
Currently CI jobs run both on `pull_request` and `push`, which causes them to run twice on each push to a PR. I restricted `on.push.branches` to `main` to prevent that.
=> fix: prevent ci jobs from running twice on pull requests

CHANGELOG.md, README.md, template/.cargo/config.toml, template/rust-toolchain.toml, template/template.yaml, xtask/src/main.rs
=> Add option to enable SSP

CHANGELOG.md, src/main.rs
Sometimes it's nice to be able to copy-paste most of the command, to either double-check selected options, or to reuse them for testing.
=> Print selected options

CHANGELOG.md, template/Cargo.toml
Update the embedded-io and embedded-io-async dependencies to utilize the `defmt-03` instead of unreachable `defmt` 
Please refer to the [document](https://docs.rs/embedded-io/0.6.1/embedded_io/#optional-cargo-features)
=> Fix embedded-io features to use defmt-03

.github/workflows/ci.yml
There is no easy way to test this, I basically copied: https://github.com/esp-rs/esp-hal/blob/main/.github/workflows/ci_nightly.yml#L46-L60
=> Open an issue if scheduled fails

CHANGELOG.md, template/src/bin/async_main.rs, template/src/bin/main.rs
Closes #156
This PR adds the lint deny to the source, so that we are able to provide a reason that is printed on the offending code. This is currently not possible to to from `Cargo.toml`.
Let me know what other lints we should specify (either allow or deny them).
=> Deny `mem::forget`

src/main.rs
This PR removes the duplicate probe-rs entry from this help text:
```
-o, --option <OPTION>            Generation options: unstable-hal, alloc, wifi, ble, embassy, stack-smashing-protection, probe-rs, probe-rs, defmt, panic-rtt-target, embedded-test, log, defmt, esp-backtrace, wokwi, dev-container, ci, helix, vscode - For more information regarding the different options check the esp-generate README.md (https://github.com/esp-rs/esp-generate/blob/main/README.md).
```
=> Deduplicate options in help text

.github/workflows/ci.yml, CHANGELOG.md, src/check.rs, src/main.rs
Closes #175
I was thinking about giving more details (the required version and/or the actual command executed) but maybe that is too much noise and not too helpful
Anyways just relying on emojis was a bit too brief
=> Explain version check results

CHANGELOG.md, template/Cargo.toml, template/src/bin/async_main.rs, template/src/bin/main.rs
`rtt_init` by default initializes 0 channels, which causes probe-rs to crash currently, and isn't useful besides.
=> Fix RTT without defmt

Cargo.lock, Cargo.toml, template/Cargo.toml, template/src/bin/async_main.rs, template/src/bin/main.rs, xtask/Cargo.lock, xtask/Cargo.toml
Also update deps of `esp-generate` and `xtask`
CI with all combinations:  https://github.com/SergioGasquez/esp-generate/actions/runs/15471797789 (fingers crossed)
2nd attempt: https://github.com/SergioGasquez/esp-generate/actions/runs/15484652222
=> Update deps to latests esp-wifi/esp-hal-embassy patch release

CHANGELOG.md, Cargo.lock, Cargo.toml, src/cargo.rs, src/check.rs, src/lib.rs, src/main.rs, template/Cargo.toml, template/src/bin/async_main.rs, template/src/bin/main.rs
Probably mostly addresses #89 by:
- Adding `rust-version` to Cargo.toml. This is a bit fragile as we need to hand-maintain it, but tools like cargo-msrv exist.
- Parsing esp-hal version out of Cargo.toml, by using largely the same code as esp-hal's release tooling. This version is then injected back into the template.
=> Substitute esp-hal's version, check MSRV based on Cargo.toml

CHANGELOG.md, Cargo.toml, README.md, src/main.rs
closes #174 
If user still will pass `--chip` and `<NAME>` in arguments, they will just proceed to our classic TUI
https://github.com/user-attachments/assets/aa3bd669-92c6-4698-85e0-2c35c03cafae
=> Add interactive flow option instead of setting target chip and name in arguments

README.md
There are a few new options available in both the CLI and the TUI:
```
-o, --option <OPTION>
Generation options: unstable-hal, alloc, wifi, ble-bleps, ble-trouble, embassy, stack-smashing-protection, probe-rs, defmt, panic-rtt-target, embedded-test, log, esp-backtrace, wokwi, dev-container, ci, helix, vscode, zed - For more information regarding the different options check the esp-generate README.md (https://github.com/esp-rs/esp-generate/blob/main/README.md).
```
This adds the options to the README.
=> docs(README): update BLE and editor feature descriptions

Cargo.lock, Cargo.toml, src/main.rs, xtask/Cargo.lock
While we don't have a licencing/type system issue here, as we've had with evalexpr in esp-config, we might as well use the same library for both.
=> Replace rhai with somni

CHANGELOG.md, src/tui.rs
- Prevent panic in tui.rs:117 triggered when the terminal shrinks.
- Launch esp-generate, enter fullscreen, and enter any MCU and project name, don't confirm yet.
- Exit fullscreen, open another terminal so the terminal is roughly half of its original size.
- Press Enter to confirm the project name; observe attempt to subtract with overflow from
src/tui.rs:117:31.
- Use core::saturating_sub when computing padding so it never goes negative, preserving
formatting without risking overflow.
=> fix panic due to padding overflow

CHANGELOG.md, template/Cargo.toml, template/src/bin/async_main.rs
**Problem description**
Cannot use [embassy-rs/trouble](https://github.com/embassy-rs/trouble) in a project created with esp-generate v0.5.0. 
**Steps to reproduce**
1) Create a new project with `esp-generate -c esp32 -o unstable-hal -o alloc -o ble-trouble -o embassy project`
2) Add the following to `main`:
```
use trouble_host::prelude::*;
let mut resources: HostResources<1, 1, 255> = HostResources::new();
let stack = trouble_host::new(_ble_controller, &mut resources);
```
3) `cargo build` produces this error:
```
error[E0277]: the trait bound `BleConnector<'_>: bt_hci::transport::Transport` is not satisfied
--> src/bin/main.rs:52:35
|
52  |     let stack = trouble_host::new(_ble_controller, &mut resources);
|                 ----------------- ^^^^^^^^^^^^^^^ the trait …
```
=> Update template with bt-hci version used by esp-wifi
